#!/usr/bin/env python
# vim: set fileencoding=utf-8 :

import vobject
import urllib2
import argparse
import sys
import commands

parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://localhost:8000/api/event/icalendar/')
parser.add_argument('--text', default=u'הצעת חוק ההגבלים העסקיים')
args = parser.parse_args(sys.argv[1:])

print repr(args.url)
urlfd = urllib2.urlopen(args.url)
txt = urlfd.read()
cal = vobject.readOne(txt)
vevents = cal.contents['vevent']
text = unicode(args.text, 'utf-8')
for ve in vevents:
    if text in ve.description.value:
        print ve.dtstart
        print(unicode.encode(ve.description.value, 'utf-8'))
